#!/usr/bin/env bash
###############################################################################
# i3-quickterm
# ============
#
# Description:           Runs i3-quickterm.
# Author:                Michael De Pasquale
# Creation Date:         2019-04-13
# Modification Date:     2019-04-13
#
###############################################################################

cd "$(dirname -- "$0")"


# These will accept aliases - assume the user knows what they are doing.
if $(command -v python3 > /dev/null); then
    exit $(python3 -m pipenv run python "main.py" "$@")
elif $(command -v python > /dev/null); then
    exit $(python -m pipenv run python "main.py" "$@")
else
    echo 'Error: could not find python or python3 commands.' >&2
    exit 1
fi

